# Generated by Django 5.2.8 on 2025-11-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of artist name', max_length=255, unique=True)),
                ('full_bio', models.TextField(blank=True, help_text='Full biography for SEO')),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('product_keywords', models.TextField(blank=True, help_text='Internal use only - product item names for search matching')),
                ('seo_tags', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500)),
                ('categories', models.JSONField(blank=True, default=list, help_text='List of selected categories')),
                ('etsy_url', models.URLField(blank=True, max_length=500)),
                ('shopify_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('tiktok_url', models.URLField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image (400x400px)', null=True, upload_to='artist_profiles/')),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='artist_banners/')),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic ($29/mo)'), ('express', 'Express ($59/mo)'), ('premium', 'Premium ($99/mo)')], default='basic', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
