# Generated by Django 5.2.8 on 2025-11-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
