# Generated by Django 5.2.8 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artistprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
