# Generated by Django 5.2.8 on 2025-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artistprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='stripe_customer_id',
        ),
    ]
