# Generated by Django 5.2.8 on 2025-11-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_remove_artistprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide profile from public listings'),
        ),
    ]
