# Generated by Django 5.2.8 on 2025-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_pendingartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Short bio for cards and summaries', max_length=255),
        ),
    ]
