# Generated by Django 5.2.8 on 2025-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_artistprofile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email', max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL', max_length=500),
        ),
    ]
