# Generated by Django 5.2.8 on 2025-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artistprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Toggle to show/hide profile from public listings'),
        ),
    ]
