# Generated by Django 5.2.8 on 2025-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_alter_artistprofile_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide profile from public listings'),
        ),
    ]
