# Generated by Django 5.2.8 on 2025-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
