# Generated by Django 5.2.8 on 2025-11-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_explorerprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerprofile',
            name='country',
        ),
    ]
