# Generated by Django 5.2.8 on 2025-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_explorerprofile_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorerprofile',
            name='street_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
