# Generated by Django 5.2.8 on 2025-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_explorerprofile_street_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='artist_banners/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image (400x400px)', null=True, upload_to='artist_profiles/'),
        ),
    ]
