# Generated by Django 5.2.8 on 2025-11-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_artistprofile_banner_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
        migrations.DeleteModel(
            name='ExplorerProfile',
        ),
    ]
