# Generated by Django 5.2.8 on 2025-11-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('street_number', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('promotion_keywords', models.TextField(blank=True, help_text='Keywords for promotions the user is interested in (e.g., Pokemon, Barbie)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explorer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
