# Generated by Django 5.2.8 on 2025-11-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
