# Generated by Django 5.2.8 on 2025-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('basic', 'Basic'), ('express', 'Express'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('price_cents', models.IntegerField(help_text='Price in cents (e.g., 2900 for $29.00)')),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of plan features')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Pricing',
                'verbose_name_plural': 'Plan Pricing',
            },
        ),
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
