# Generated by Django 5.2.8 on 2025-12-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitor',
            name='user_agent',
        ),
    ]
