# Generated by Django 5.2.8 on 2025-12-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_remove_sitevisitor_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
