# Generated by Django 5.2.8 on 2025-12-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_sitevisitor_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitor',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='sitevisitor',
            name='session_key',
        ),
    ]
