# Generated by Django 5.2.8 on 2025-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_remove_sitevisitor_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
