# Generated by Django 5.2.8 on 2025-12-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_sitevisitor_referrer_sitevisitor_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='visit_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
