# Generated by Django 5.2.8 on 2025-12-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_sitevisitor_visit_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitor',
            name='visit_data',
        ),
    ]
