# Generated by Django 5.2.8 on 2025-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_remove_sitevisitor_visit_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpricing',
            name='features',
        ),
    ]
