# Generated by Django 5.2.8 on 2025-12-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_remove_planpricing_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpricing',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of plan features'),
        ),
    ]
