# Generated by Django 5.2.8 on 2025-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0010_planpricing_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the announcement (e.g. Christmas Offer)', max_length=50),
        ),
    ]
